### ISSUE TITLE
Update Layout

### ISSUE THREAD

**Issue by adrianreza96** [adrianreza96/team1#18]
Modify website layout to reflect the project.

- [ ] Update Navbar

> Add Kitchens
Add Profile Page
Add Login
Add Logout
Add application name to the front
Remove unnecessary links

- [ ] Update Home page to allow better navigation
> TBD

**Comment by angulu** [comment]
I have changed to navbar. Added log in, kitchens and menus. Will add logout, car, and profile icon after pulling the user controller.
Also, worked on the landing page on home controller.

**Comment by angulu** [comment]
Completed. Will push in the morning.
