### ISSUE TITLE
Create Kitchen Controller & Model

### ISSUE THREAD

**Issue by adrianreza96** [adrianreza96/team1#2]
Kitchen Database Tabel Design
![kitchenDatabaseDesign](https://user-images.githubusercontent.com/22806429/84932105-62a9c700-b099-11ea-8f0d-0ff84b096859.PNG)

**Comment by angulu** [comment]
I have created the controller and model in a branch; I have some issues pushing the changes.

**Comment by angulu** [comment]
successfully pushed changes; waiting for approval.

**Comment by angulu** [comment]
approved and merged.
